### ISSUE TITLE
"make all"  can't find file or dir

### ISSUE THREAD

**Issue by rnsrk** [FAU-CDI/drincw#2]
Hi, during installation step "make all", an error is thrown: "
`make: lipo: Cannot find File or Directory
make: *** [Makefile:19: dist/addict_darwin] Fehler 127`

**Comment by rnsrk** [comment]
You have to download the binaries from the releases as a workaround by the way

**Comment by tkw1536** [comment]
This should have been fixed by running `make deps` as explained in the README. 
`lipo` not being found indicates that the go installation is not entirely configured; in particular `$GOBIN` or `$GOPATH/bin` was missing from `$PATH` .
I've nonetheless implemented a workaround in bb0e23f1ca2c86ba0f93d9b6a1754669f5f1c106.
